package dev.zynema.gateway.config;

import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Programmatic route definitions.
 *
 * <p>Service ids are resolved through Eureka, so no host or port is hardcoded.
 * The public API is versioned ({@code /api/v1/...}, ADR-0004) and routes do
 * <strong>not</strong> strip a prefix: the path a client calls is the path the
 * service receives, which keeps the gateway transparent and the OpenAPI specs
 * generated by each service directly usable.
 */
@Configuration
public class GatewayRoutesConfig {

    @Bean
    public RouteLocator customRoutes(RouteLocatorBuilder builder) {
        return builder.routes()
            // ─── BFF: the frontend's single entry point (Fase 5) ───
            .route("bff-web", r -> r
                .path("/api/v1/web/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("bff-cb")))
                .uri("lb://bff-service"))

            // ─── Auth: public endpoints and the rest of the auth API ───
            .route("auth-public", r -> r
                .path("/api/v1/auth/public/**")
                .uri("lb://auth-service"))

            .route("auth", r -> r
                .path("/api/v1/auth/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("auth-cb")))
                .uri("lb://auth-service"))

            // ─── Domain services ───
            .route("catalog", r -> r
                .path("/api/v1/catalog/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("catalog-cb")))
                .uri("lb://catalog-service"))

            .route("user", r -> r
                .path("/api/v1/users/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("user-cb")))
                .uri("lb://user-service"))

            .route("payment", r -> r
                .path("/api/v1/payments/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("payment-cb")))
                .uri("lb://payment-service"))

            .route("playback", r -> r
                .path("/api/v1/playback/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("playback-cb")))
                .uri("lb://playback-service"))

            .route("notification", r -> r
                .path("/api/v1/notifications/**")
                .filters(f -> f.circuitBreaker(cb -> cb.setName("notification-cb")))
                .uri("lb://notification-service"))

            // ─── Aggregated API docs ───
            .route("swagger", r -> r
                .path("/v3/api-docs/**", "/swagger-ui/**", "/swagger-ui.html")
                .uri("lb://api-gateway"))

            .build();
    }
}
